# Generated by Django 6.0.4 on 2026-04-29 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_mockinterview_interviewsession_mock_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterview",
            name="performance_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="total_time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="QuestionPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("time_spent", models.IntegerField(default=0)),
                ("code", models.TextField(blank=True, default="")),
                (
                    "language",
                    models.CharField(blank=True, default="python", max_length=20),
                ),
                ("interview_brief", models.TextField(blank=True, default="")),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mock_interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="api.mockinterview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.question"
                    ),
                ),
            ],
        ),
    ]
